name: CI

on:
  release:
    types: [published]
  pull_request:
    branches: '**'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  image-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Unpack build
      run: |

    - name: Build Docker image for PRs
      run: |
        LOWERCASE_REPOSITORY=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
        IMAGE_NAME="actions-playground"

        IMAGE_NAME="ghcr.io/${LOWERCASE_REPOSITORY}/${IMAGE_NAME}:pr-${{ github.event.number }}"

        echo "Build official Docker image ${IMAGE_NAME}"

        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
