name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  image-build:
    runs-on: ubuntu-latest
    needs: deploy

    strategy:
      matrix:
        release: ["official", "preview"]

    steps:
    - name: Unpack build
      run: |

        export DOCKER_PATH="${GITHUB_WORKSPACE}/.docker"
        if [[ '${{ matrix.release }}' = 'preview' ]]; then
          export DOCKER_PATH="${DOCKER_PATH}-mongo"
        fi;

        echo "la vai"
        echo $DOCKER_PATH
